<a href="https://colab.research.google.com/github/zsert1/-Natural_language_processing/blob/main/%EA%B2%BD%EC%82%AC%ED%95%98%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. 선형회귀 구현

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optiom

In [2]:
# 파이썬 코드를 재실행하여도 같은 결과 나오도록
# 랜덤 시드 1 부여
torch.manual_seed(1)

훈련 데이터 생성

In [3]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])


x_train과 x_train 크기를 확인하기 위해 shape 출력

In [5]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


shape은 행렬로 보면 되고 3*1 임을 알 수 있다

In [6]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


선형회귀 학습이란 학습데이터와 가장 잘 맞는 직선을 찾는 것
직선을 정의하는 것은 w,b이며 가장 잘 맞는 w(가중치),b(편향도)를 찾는 것이 목표이다

In [7]:
# 가중치 W를 0으로 두어 초기화 후 학습을 통해 값이 변경되는 변수임을 명시
W=torch.zeros(1,requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


requires_grad= True 라는 것은 학습을 통하여 값이 계속 변경되는 변수를 의미

In [8]:
b=torch.zeros(1,requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


현재 W,b는 0이므로 직선의 방정식은 y=0X x+0 이므로 적절한 W,b의 값이 아니다

In [9]:
hypothesis=x_train*W+b

파이토치는 코드상 선형회귀의 비용 함수에 해당되는 평군 제곱 오차를 계산한다.

In [10]:
cost=torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


경사하강법을 구현하며 **SGD**는 경사하강법의 일종이며 Ir은 학습률을 의미한다.
학습 대상인 W,b가 SGD의 입력된다.

In [11]:
optimizer=optiom.SGD([W,b],lr=0.01)

optimizer.zero_grad()를 실행하여 미분통해 얻은 기울기 0으로 초기화.
=> 가중치 편향에 대한 새로운 기울기 구하기 위하여  
cost.backward()를 통하여 가중치와 편향에 대한 기울기 계산 그후 step()를 통하여 인수로 들어간 W,b에서 리턴되는 변수들의 기울기에 학습률 0.01씩 곱하여 빼줌으로서 업데이트

In [12]:
optimizer.zero_grad()
# 비용함수 미분하여 기울기 계산
cost.backward()
# W,b업데이트
optimizer.step()

훈련과정을 통해 W와b는 훈련 데이터와 잘 맞는 직선을 표현하기 위한 적절한 값으로 변화해 간다.

In [13]:
np_eoichs=1999
for eoich in range(np_eoichs+1):
  hypothesis=x_train*W+b
  cost=torch.mean((hypothesis-y_train)**2)
  # cost로 H(x)계산
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if eoich%100 == 0:
    print('Epoch{:4d}/{} W:{:.3f},b:{:.3f} Cost:{:.6f}'.format(eoich,np_eoichs,W.item(),b.item(),cost.item()
    ))

Epoch   0/1999 W:0.353,b:0.151 Cost:14.770963
Epoch 100/1999 W:1.746,b:0.577 Cost:0.047939
Epoch 200/1999 W:1.801,b:0.453 Cost:0.029624
Epoch 300/1999 W:1.843,b:0.356 Cost:0.018306
Epoch 400/1999 W:1.877,b:0.280 Cost:0.011312
Epoch 500/1999 W:1.903,b:0.220 Cost:0.006990
Epoch 600/1999 W:1.924,b:0.173 Cost:0.004319
Epoch 700/1999 W:1.940,b:0.136 Cost:0.002669
Epoch 800/1999 W:1.953,b:0.107 Cost:0.001649
Epoch 900/1999 W:1.963,b:0.084 Cost:0.001019
Epoch1000/1999 W:1.971,b:0.066 Cost:0.000630
Epoch1100/1999 W:1.977,b:0.052 Cost:0.000389
Epoch1200/1999 W:1.982,b:0.041 Cost:0.000240
Epoch1300/1999 W:1.986,b:0.032 Cost:0.000149
Epoch1400/1999 W:1.989,b:0.025 Cost:0.000092
Epoch1500/1999 W:1.991,b:0.020 Cost:0.000057
Epoch1600/1999 W:1.993,b:0.016 Cost:0.000035
Epoch1700/1999 W:1.995,b:0.012 Cost:0.000022
Epoch1800/1999 W:1.996,b:0.010 Cost:0.000013
Epoch1900/1999 W:1.997,b:0.008 Cost:0.000008


## 2.torch.manual_seed() 하는 이유

torch.manual_seed()를 사용한 프로그램의 결과는 다른 컴퓨터에서 실행시켜도 동일한 결과를 얻는다.
torch.manual_seed()가 난수 발생 순서와 값을 동일하게 보장해주기 때문이다.

## 3.optimizer.zero_grad() 하는 이유

파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있다.